# python -c 'import secrets; print(secrets.token_hex())'
SECRET_KEY = "dev"
MSF_API_CLIENT_ID = "YOUR ID"
MSF_API_CLIENT_SECRET = "YOUR SECRET"
MSF_API_REDIRECT_URI = "YOUR REDIRECT URI"
SERVER_NAME = "YOUR SERVER NAME"
PREFERRED_URL_SCHEME = "https"